services:
  db:
    build: ./docker/postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tpch

    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c shared_buffers=512MB
      -c work_mem=16MB

    ports:
      - "5433:5432"

    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
